plugins {
    id 'hiro.MyApp2'
}

android {
    namespace 'hiro.MyApp2'
    compileSdk 34

    defaultConfig {
        applicationId "hiro.MyApp2"
        minSdk 1
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
